project:
  type: website
  output-dir: docs

website:
  title: "AI-Careers-Group4"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Project Overview"
        href: project-overview.qmd
      - text: "Bibliography Section"
        href: bibliography.qmd
      - text: "Data Analysis"
        href: data_analysis.qmd
      - text: "Skill Gap Analysis"
        href: skill_gap_analysis.html
      - text: "Regression Insights"
        href: models
      - text: "KMeans Insights"
        href: kmeans

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




